statler/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^api/', include('statler_api.urls', namespace="api")),
    url(r'^util/', include('statler_util.urls', namespace="util")),
    url(r'^admin/', include(admin.site.urls)),
    
    # Default to statler_site
    url(r'^', include('statler_site.urls', namespace="site")),
]

statler_api/urls.py
from django.conf.urls import url
# Reference the views contained in this app.
from . import views

# This is where the magical regex mapping happens.
urlpatterns = [
    # urls that look like /api/health-check/ are forwarded to
    # the views.healthCheck function
    url(r'^health-check/$', views.healthCheck, name='health-check'),

    # urls that look like /api/play/<play_id>/ are forwarded to
    # the views.getPlayDetail function
    url(r'^play/(?P<play_id>[^,/]+)/$', views.getPlayDetail, name='play-detail'),
    
    # urls that look like /api/play-list/<play_list_id> are forwarded to
    # the views.getPlayList function
    url(r'^play-list/(?P<play_list_id>[^,/]+)/$', views.getPlayList, name='play-list'),

    # posts to /api/play/<play_id>/reviews/ are handled here
    url(r'^play/(?P<play_id>[^,/]+)/reviews/$', views.postReview, name='play-reviews')
]

statler_site/urls.py
from django.conf.urls import url
# Reference this app's views.
from . import views

# This is where the magical regex mapping happens.
urlpatterns = [
    # urls that look like 'health-check/'
    url(r'^health-check/$', views.healthCheck, name='health-check'),

    # urls that look like 'play/<play_id>/'
    url(r'^play/(?P<play_id>[^,/]+)/$', views.getPlayDetailPage, name='play-detail'),

    # urls that look like 'play-list/<play_list_id>/'
    url(r'^play-list/(?P<play_list_id>[^,/]+)/$', views.getPlayListPage, name='play-list'),

    # urls that look like 'about/'
    url(r'^about/$', views.getAboutPage, name='about'),

    # blank urls are forwarded to the getLandingPage function
    url(r'^$', views.getLandingPage, name='play-list'),
]

statler_site/views.py
from django.shortcuts import render
from django.http import HttpResponse

def healthCheck(request):
    """Returns a string. This shouldn't break. We can use this
    to confirm the server is on its feet."""
    return HttpResponse("The site is alive.")

def getPlayListPage(request, play_list_id):
    """returns an html page which will use JavaScript
    to get and display data"""
    return render(request, 'play-list-page.html', {'play_list_id': play_list_id})

def getPlayDetailPage(request, play_id):
    """returns an html page which will use JavaScript
    to get and display data"""
    return render(request, 'play-detail-page.html', {'play_id': play_id})

def getLandingPage(request):
    """returns an html page which will use JavaScript
    to get and display data"""
    return render(request, 'landing-page.html', {})

def getAboutPage(request):
    return render(request, 'about.html', {})

statler_site/templates/about.html
{% extends "statler-base-page.html" %}

{% block main-content %}
    <div class="container">
      <div class="about-page-text">
        <h1>About <i>Ten! Ten! Ten!</i></h1>
        <p>
          <i>Ten! Ten! Ten!</i> is the final directing project for THEA 370: Directing of the Stage. <i>Ten! Ten! Ten!</i> has been a theatre tradition at George Fox University for the past 15 years. For more information about GFU Theatre go to <a href="http://theatre.georgefox.edu">theatre.georgefox.edu</a>.
        </p>
        <h1>About the CABAM Team</h1>
        <p>
          tententenreviews.com is the product of a semester-long project for GFU's Software Engineering class. Our task was to create a system that would rank products like movies or plays based on a sentiment analysis of user reviews, instead of a numbered ranking system like "stars." We thought it would be a great learning experience (and a fun challenge!) for us to make the system a real product used by real people, so we contacted the Theater Department to see if they would like to be our client. For some reason, they did, and we're thrilled to present to you a site specially designed for <i>Ten! Ten! Ten!</i> reviews.
        </p>
      </div>
    </div>
{% endblock %}

statler_site/templates/landing-page.html
{% extends "statler-base-page.html" %}

{% block page-script %}
    <script>

      // This script makes an API call and displays the returned data

      // jQuery code normally starts with the .ready function
      $(document).ready(function(){
        fillInList("/api/play-list/wednesday-chronological/", "#play-list-wednesday");
        fillInList("/api/play-list/thursday-chronological/", "#play-list-thursday");
      });

      function fillInList(getURL, divId) {
        // Get JSON from a URL as an object
        $.getJSON(getURL, function(result){
          // remove the loading gif
          $(divId).empty();

          // display the returned json dynamically
          $.each(result, function(i, playEntry){
            var play = playEntry.play;
            var index = playEntry.index;

            // TODO: order plays in some way?

            $(divId).append(
              $('<div class="landing-page-play-entry" />').append(
                $('<a />', {href: '/play/' + play.url_title}).append(
                  $('<img />', {width: '120', height: '120', src: '/' + play.image_url})
                )
              ).append(
                $('<p />').append(
                  $('<a />', {href: '/play/' + play.url_title}).append(
                    play.title
                  )
                )
              )
            );

          });
        });
      }

    </script>
{% endblock %}

{% block main-content %}
    <div class="container">
      <p class="landing-page-text">Click a play to review it . . .</p>
      <div class="landing-page-list-box">
        <p class="landing-page-text">Wednesday Night:</p>
        <div class="landing-page-list" id="play-list-wednesday">
          <img src="/static/loading.gif" />
        </div>
        <p class="landing-page-text">Thursday Night:</p>
        <div class="landing-page-list" id="play-list-thursday">
          <img src="/static/loading.gif" />
        </div>
      </div>
      <div style="text-align:center">
        <span class="landing-page-button">
          <a href="/play-list/all/">View Play Rankings</a>
        </span>
      </div>
    </div>
{% endblock %}

statler_site/templates/play-detail-page.html
{% extends "statler-base-page.html" %}

{% block page-script %}
    <script>
      // This script makes an API call and displays the returned data

      // This string will be filled out by Django when the page is served.
      // It contains the URL to make an API call to
      var apiEndpointUrl = "{% url 'api:play-detail' play_id %}";

      // jQuery code normally starts with the .ready function
      $(document).ready(function(){
        // Test if a cookie exists
        if(Cookies.get("post") != undefined)
        {
           // call the postSuccsess method again with the response saved in the cookie
           var response = {text:Cookies.get("post")};
           postSuccess(response);
        }

        // Get JSON from a URL as an object
        $.getJSON(apiEndpointUrl, function(result){
          // display the returned json dynamically

          // fill in page title
          $(".header > h1").append(result.title);
          // fill in description
          $('#play-image-div').append(
            $('<img/>', {width: '120', height: '120', src: '/' + result.image_url})
          );
          $('#description').append(
            $("<p/>").append(result.description)
          );
          $('#details').append(
            $("<p/>").append("Directed by ", result.director),
            $("<p/>").append("Actors: ", result.actors),
            $("<p/>").append(result.show_times)
          );
          // fill in reviews
          $.each(result.reviews, function(index, review) {
            $("#review-list").append(
              $('<div class="panel my-panel"/>').append(
                review.text
              )
            );
          });
          // Add a heading saying 'Top Reviews:' only if there are some
          if (result.reviews.length > 0) {
            $('#top-reviews').html('Top Reviews:');
          }

        });
      });

      //function for posting review
      function postReview() {
        $.ajax({
          url: "{% url 'api:play-reviews' play_id %}",
          type: 'post',
          data: JSON.stringify({text: $("#post-box").val()}),
          // Set a header containing the crsf token to prevent crsf attacks
          // django requires this and handles it automatically
          // see https://docs.djangoproject.com/en/1.8/ref/csrf/#ajax
          headers: {"X-CSRFToken": "{{ csrf_token }}"},
          // type sent to server
          contentType: "application/json; charset=UTF-8",
          // type expected back from server
          dataType: "json",
          success: postSuccess,
          error: postError
        });
      }

      function postSuccess(response) {
         // if this is the first time posting build a cookie with the posted respsone
         if(Cookies.get("post") == undefined)
         {
            Cookies.set("post", response.text, { expires: 365, path: '' });
         }
      
        $("#post-box-div").html(
          $('<div class="panel panel-success"/>').append(
            $('<div class="panel-heading"/>').append(
              "Thank you for reviewing this play. Your review has been recorded."
            )
          ).append(
            $('<div class="panel-body"/>').append(
              response.text
            )
          )
        );
      }

      function postError(response) {
        $("#post-box-div").prepend(
          $('<div class="alert alert-danger"/>').append(
            "An error occured while posting your review."
          )
        );
      }

    </script>
{% endblock %}

{% block header-title %}{% comment This will get filled in by AJAX %}{% endcomment %}{% endblock %}

{% block main-content %}
    <div class="container">
      <div id="play-image-div"></div>
      <div id="description"></div>
      <div id="details"></div>
      <div id="post-box-div">
        <textarea id="post-box" class="form-control" rows="5" placeholder="Enter your review here. . . Our robots will rank the play based on what you say."></textarea>
        <div style="text-align: right">
          <button onclick="postReview()">Submit</button>
        </div>
      </div>
      <div id="review-list">
        <p id="top-reviews"></p>
      </div>
    </div>
{% endblock %}

statler_site/templates/play-list-page.html
{% extends "statler-base-page.html" %}

{% block page-script %}
    <script>

      // This script makes an API call and displays the returned data

      // This string will be filled out by Django when the page is served.
      // It contains the URL to make an API call to
      var apiEndpointUrl = "{% url 'api:play-list' play_list_id %}";

      // jQuery code normally starts with the .ready function
      $(document).ready(function(){
        // Get JSON from a URL as an object
        $.getJSON(apiEndpointUrl, function(result){
          // display the returned json dynamically
          $.each(result, function(i, playEntry){
            var play = playEntry.play;
            var index = playEntry.index;

            // this indentation helps because it looks a bit like html
            $('#play-list').append(
              //the whole list item is a link to the play description page
                $('<div class="row panel my-panel"/>').append(
                  $('<div class="play-list-entry-index col-sm-1" />').append(
                    // display the play's index, or a question mark if it is not ranked
                    index ? index : '?'
                  ),
                  $('<div class="col-sm-11" />').append(
                    $('<img/>', {class: "play-list-image", src: '/' + play.image_url}),
                    $('<h1/>').append(play.title),
                    $('<p/>').append('Directed by ', play.director),
                    $('<p/>').append(play.show_times)
                  ),
                  $('<a class="whole-div-link" href="/play/' + play.url_title + '/" />')
                )
            );

          });
        });
      });

    </script>
{% endblock %}

{% block main-content %}
    <div class="container">
      <p id="description">Plays ranked by review positivity:</p>
      <div id="play-list" class="container">
      </div>
    </div>
{% endblock %}

statler_site/templates/statler-base-page.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="/static/js.cookie.js"></script>

    <link href="/static/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/styles.css"/>

    <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/static/favicon.ico" type="image/x-icon">

    {% block page-script %}
        <script></script>
    {% endblock %}

    <title>{% block page-title %}Ten! Ten! Ten! Reviews{% endblock %}</title>

</head>
<body>

<div class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="/" class="navbar-brand">Ten! Ten! Ten!</a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#statler-navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="statler-navbar-collapse">
            <ul class="nav navbar-nav navbar-left">
                <li><a href="{% url "site:play-list" "wednesday" %}">Wednesday</a></li>
                <li><a href="{% url "site:play-list" "thursday" %}">Thursday</a></li>
                <li><a href="{% url "site:play-list" "all" %}">All Plays</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url "site:about" %}">About</a></li>
            </ul>
        </div>
    </div>

</div>
</div>

<div class="header" style="background-image:url('/static/header-image.jpg')">
    <img class="logo-overlay" src="/static/gfu-logo.png"/>

    <h1>{% block header-title %}Ten! Ten! Ten!{% endblock %}</h1>
</div>
{% block main-content %}
    <div class="container"></div>
{% endblock %}
</body>
</html>