statler/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^api/', include('statler_api.urls', namespace="api")),
    url(r'^util/', include('statler_util.urls', namespace="util")),
    url(r'^admin/', include(admin.site.urls)),
    
    # Default to statler_site
    url(r'^', include('statler_site.urls', namespace="site")),
]

statler_util/urls.py
from django.conf.urls import url
# Reference the views contained in this app.
from . import views

# This is where the magical regex mapping happens.
urlpatterns = [
    url(r'^report/$', views.getSimplePlayIndex, name='report-index'),
    url(r'^report/(?P<play_id>[^,/]+)/$', views.getDirectorsReport, name='report'),

    url(r'^approve/$', views.getSimplePlayIndex, name='approve-index'),
    url(r'^approve/(?P<play_id>[^,/]+)/$', views.getApprovalPage, name='approve'),
    url(r'^approved/(?P<play_id>[^,/]+)/reviews/$', views.postApprovedReviews, name='approved-reviews'),
]

statler_util/views.py
import json  # Python builtin
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from statler_api.models import PlayList, Play

@login_required(login_url="/admin/login/")
def getSimplePlayIndex(request):
    """the simple play index is a page with a list of all plays, each with link to a that
    play's url_title as a relative url. That means that if the page is served at /some-url/
    the links will go to /some-url/play-url/. This page is served at both /util/report/
    and /util/approve/"""
    
    all_plays = get_object_or_404(PlayList, url_title="all")
    return render(request, 'util/simple-index.html', {'all_plays': all_plays})

@login_required(login_url="/admin/login/")
def getDirectorsReport(request, play_id):
    play = get_object_or_404(Play, url_title=play_id)
    reviews = play.review_set.order_by('timestamp')
    return render(request, 'util/directors-report.html', {'play': play, 'reviews': reviews})

@login_required(login_url="/admin/login/")
def getApprovalPage(request, play_id):
    """returns an html page which will facilitate approval of reviews"""

    play = get_object_or_404(Play, url_title=play_id)
    alreadyTop = list(play.review_set.filter(top_review_rank__isnull=False).order_by("top_review_rank"))


    return render(
        request,
        'util/review-approval-page.html',
        {
            'play': play,
            'top1': alreadyTop[0] if len(alreadyTop) > 0 else None,
            'top2': alreadyTop[1] if len(alreadyTop) > 1 else None,
            'top3': alreadyTop[2] if len(alreadyTop) > 2 else None,
})


@login_required(login_url="/admin/login/")
def postApprovedReviews(request, play_id):
    """Accept the top reviews as JSON"""

    approved = json.loads(request.body.decode('utf-8'))

    play = get_object_or_404(Play, url_title=play_id)
    reviews = play.review_set
    reviews.update(top_review_rank=None)

    numApproved = 0

    if (approved):
        if approved["top-1"]:
            top1 = reviews.get(pk=approved["top-1"])
            top1.top_review_rank = 1
            top1.save()
            numApproved += 1

        if approved["top-2"]:
            top2 = reviews.get(pk=approved["top-2"])
            top2.top_review_rank = 2
            top2.save()
            numApproved += 1

        if approved["top-3"]:
            top3 = reviews.get(pk=approved["top-3"])
            top3.top_review_rank = 3
            top3.save()
            numApproved += 1
        
    return JsonResponse({ "message": "Success! " + str(numApproved) + " reviews approved." })

statler_util/templates/util/directors-report.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--bootstrap old and new support broswers-->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"/>
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- Latest compiled and minified CSS -->

    <style type="text/css">
      .well {
          background-color: white;
          border: 1px solid black;
          word-wrap: break-word;
      }

      .jumbotron p {
          margin: 15px;
      }

      .jumbotron h1 {
          margin: 0px;
      }
    </style>
</head>
<body>
<div class="jumbotron" style="background-color: white; text-align: center;">
    <div class="container" style="border-bottom: 5px solid black; border-top: 5px solid black;" >
        
    <p><em>Ten! Ten! Ten!</em> review report</p>
    <h1>{{ play.title }}</h1>
    <p>Directed by {{ play.director }}</p>
    </div>

</div>

<div class="container">
    <div style="position: relative;">
        <h1>Reviews</h1>
        <p style="font-style: italic; text-align: right; position: absolute; bottom: 0px; right: 0px; margin: 0px;">
            Computer-generated review rating<strong>*</strong><br />
            (reviews displayed on website are starred)
        </p>

     </div>      
        {% for review in reviews %}

        <div class="row well" style="{page-break-inside: avoid;}">
            {% comment %} Review text is already escaped, don't escape it again {% endcomment %}
            <div class="col-xs-9">
                {% autoescape off %}{{ review.text }}{% endautoescape %}
            </div>
            <div class="col-xs-3" style="font-style: italic; text-align: right;">

                {% if review.top_review_rank != None %}
                <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
                {% endif %} 

                {% if review.rating > 0 %}
                Positive ({{ review.rating|floatformat:0 }}% confidence)
                {% elif review.rating < 0 %}
                Negative ({{ review.rating|floatformat:0|slice:"1:" }}% confidence)
                {% else %}
                Neutral
                {% endif %}
            </div>
        </div>
        {% endfor %}

        <div id="disclaimer">
            
        <p style="font-style: italic;">
            <strong>*</strong> The computer-generated rating is derived from automated sentiment analysis of the reviews' text. 
            Natural language processing is one of the modern frontiers of computer science, so take our rating robot's guess
            with a grain of salt. Our team manually chose the top reviews (starred) to be displayed on the site.
        </p>

        <p style="font-size: large; text-align: center;"> 
            It has been a pleasure to work with you throughout <em>Ten! Ten! Ten!</em> If you have any questions about the site,
            don't hesitate to reach out to <em>tententenreviews@gmail.com</em>
        </p>
        <p style="font-size: large; text-align: center;">
            Sincerely,<br />
            Team CABAM
        </p>
        </div>
</div>
</body>
</html>

statler_util/templates/util/review-approval-page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--bootstrap old and new support broswers-->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"/>
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- Latest compiled and minified CSS -->

    <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/static/favicon.ico" type="image/x-icon">

    <script>
        function makeFirst(id) {

            var firstPk = $("#top-1 .pk").html();
            if (firstPk)
            {
                makeSecond(firstPk);
            }

            var text = $("#" + id + " .review-text").html();
            $("#top-1 .review-text").html(text);
            $("#top-1 .pk").html(id);
        }

        function makeSecond(id) {

            var secondPk = $("#top-2 .pk").html();
            if (secondPk)
            {
                makeThird(secondPk);
            }

            var text = $("#" + id + " .review-text").html();
            $("#top-2 .review-text").html(text);
            $("#top-2 .pk").html(id);
        }

        function makeThird(id) {
            var text = $("#" + id + " .review-text").html();
            $("#top-3 .review-text").html(text);
            $("#top-3 .pk").html(id);
        }

        function sumbitTop()
        {

            var topPlays = {
                "top-1": $("#top-1 .pk").html(),
                "top-2": $("#top-2 .pk").html(),
                "top-3": $("#top-3 .pk").html()
            };

            function postSuccess(data)
            {
                $("#post-alert").addClass("alert-success").html(data.message).show();
            }
            function postError(error)
            {
                $("#post-alert").addClass("alert-danger").html(error).show();
            }

            $.ajax({
                url: "{% url 'util:approved-reviews' play.url_title %}",
                type: 'post',
                data: JSON.stringify(topPlays),
                headers: { "X-CSRFToken": "{{ csrf_token }}" },
                contentType: "application/json; charset=UTF-8",
                dataType: "json",
                success: postSuccess,
                error: postError
            });
        }
    </script>

    <style>
        #all-review-column {
            position: absolute;
            left: 0px;
            top: 0px;
        }

        #top-review-column {
            position: fixed;
            right: 0px;
            top: 0px;
        }
        
        .btn-first, .btn-second, .btn-third {
            width: 100%
        }

    </style>

    <title>Review Play</title>
</head>

<body>
<div class="col-md-6" id="all-review-column">
            <h1>Approve {{ play.title }} reviews</h1>

            {% for review in play.review_set.all %}
                <div class="row" id="{{ review.pk }}">
                    <div class="col-md-2">
                        <button class="btn btn-default btn-first" onclick="makeFirst({{ review.pk }})">1</button>
                        <button class="btn btn-default btn-second" onclick="makeSecond({{ review.pk }})">2</button>
                        <button class="btn btn-default btn-third" onclick="makeThird({{ review.pk }})">3</button>
                        <div class=""></div>
                    </div>
                    <div class="col-md-10 well review-text">{{ review.text }}</div>
                </div>
                <hr>

            {% endfor %}

        </div>

        <!-- This column contains the current top reviews -->
        <div class="col-md-6" id="top-review-column">
            <h1>Top Reviews</h1>

            <div id="top-1" class="row">
                <div class="col-md-2">
                    <h2>1</h2>
                    <h3 class="pk">{{ top1.pk }}</h3>
                </div>
                <div class="col-md-10 review-text well">{{ top1.text }}</div>
            </div>
            <hr>
            <div id="top-2" class="row">
                <div class="col-md-2">
                    <h2>2</h2>
                    <h3 class="pk">{{ top2.pk }}</h3>
                </div>
                <div class="col-md-10 review-text well">{{ top2.text }}</div>
            </div>
            <hr>
            <div id="top-3" class="row">
                <div class="col-md-2">
                    <h2>3</h2>
                    <h3 class="pk">{{ top3.pk }}</h3>
                </div>
                <div class="col-md-10 review-text well">{{ top3.text }}</div>
            </div>
            <hr>

            <button id="submit-button" onclick="sumbitTop()" class="btn large btn-primary" style="width: 100%">Submit</button>
            <div id="post-alert" class="alert" style="display:none"></div>
        </div>
</body>
</html>

statler_util/templates/util/simple-index.html
{% for play in all_plays.plays.all %}
  <p><a href="{{ play.url_title }}"> {{ play.title }} </a></p>
{% endfor %}